### ISSUE TITLE
Inconsistencia en campos en igj-entidades-YYYY-MM.csv y campos documentados

### ISSUE THREAD

**Issue by fstilman** [datos-justicia-argentina/Entidades-constituidas-en-la-Inspeccion-General-de-Justicia#1]
En el CSV los campos son:

"numero_correlativo","tipo_societario","descripcion_tipo_societario","razon_social","dada_de_baja","codigo_baja","detalle_baja"

En la documentación se omite la descripción de los campos "dada_de_baja", "codigo_baja" y "detalle_baja", y por otro lado se documenta un campo "informada_como_inactiva" que no existe en el archivo CSV.

La documentación actualmente dice: 

### Campos del recurso
-   **numero_correlativo (int):** número correlativo que identifica la entidad
-   **tipo_societario (int):** código del tipo societario
-   **descripcion_tipo_societario (string):** descripción del tipo societario
-   **razon_social (string):** razón social de la entidad
-   **informada_como_inactiva (string):** toma valor "S" si la entidad forma parte del Registro de Entidades Inactivas (incuído a partir de 2016-10)

**Comment by jsadi** [comment]
Muchas gracias! Ya está solucionado

### Campos del recurso

-   **numero_correlativo (int):** número correlativo que identifica la entidad

-   **tipo_societario (int):** código del tipo societario

-   **descripcion_tipo_societario (string):** descripción del tipo societario

-   **razon_social (string):** razón social de la entidad

-   **dada_de_baja (string):** toma valor "S" si la entidad forma parte del Registro de Entidades Inactivas (incuído a partir de 2016-10)

-   **codigo_baja (int):** código que identifica la baja

-   **detalle_baja (string):** descripción del motivo de la baja
